[helpers]

[settings]
default_target_type = "automatic"



[default]
[default.files]
"config/xremap.yml" = "~/.config/xremap/config.yml"
"config/fonts.conf" = "~/.config/fontconfig/fonts.conf"
"config/xdg-desktop-portal/niri-portals.conf" = "~/.config/xdg-desktop-portal/niri-portals.conf"
"config/qt6ct" = "~/.config/qt6ct"

[niri.files]
"config/niri" = "~/.config/niri/"
[niri.variables]
resolution = "1920x1280@60"
scale = "1.6"
cursor_theme = "breeze_cursors"
cursor_size = "27"
[nvim]
[nvim.files]
"config/nvim" = "~/.config/nvim"
[terminal]
[terminal.files]
"config/yazi" = "~/.config/yazi"
"config/alacritty" = "~/.config/alacritty/"
"zsh/.zshrc" = "~/.zshrc"
# "zsh/theme-starship.toml" = "~/.config/starship.toml"
"zsh/theme-p10k.zsh" = "~/.p10k.zsh"
[terminal.variables]
font_size = "12"
