[helpers]

[settings]
default_target_type = "automatic"



[default]
[default.files]
"config/xremap.yml" = "~/.config/xremap/config.yml"
"config/fonts.conf" = "~/.config/fontconfig/fonts.conf"
[niri.files]
"config/niri" = "~/.config/niri/"
[niri.variables]
resolution = "1920x1280@60"
scale = "1.6"
cursor_theme = "BreezeX-Black"
cursor_size = "32"
[nvim]
[nvim.files]
"config/nvim" = "~/.config/nvim"
[terminal]
[terminal.files]
"config/yazi" = "~/.config/yazi"
"config/alacritty" = "~/.config/alacritty/"
[terminal.variables]
font_size = "12"
